apps/blog/urls.py
# coding:utf-8

from django.conf.urls import url
from blog import views
from django.views.decorators.cache import cache_page  # 缓存
import search_views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^qrcode$', views.generate_qrcode, name='qrcode'),
    # 如果用 r'^article/(?P<article_id>\d+)'，则文章无法评论
    url(r'^article/(?P<article_id>\d+)$',
        views.ArticleDetailView.as_view(), name='detail'),
    url(r'^article/(?P<article_id>\d+)/praise$',
        views.praise, name='praise'),
    url(r'^article/(?P<article_id>\d+)/upload$',
        views.upload, name='upload'),
    url(r'^article/(\d+)/download/(\d+)$',
        views.download, name='download'),
    url(r'^category/(?P<cate_id>\d+)$',
        views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$',
        views.ArchiveView.as_view(), name='archive'),
    url(r'^article/(?P<article_id>\d+)/comment/$',
        views.CommentPostView.as_view(), name='comment'),
    url(r'^login', views.LoginView.as_view(), name='login'),
    url(r'^account$', views.AccountView.as_view(), name='account'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^regist$', cache_page(60)(views.regist), name='regist'),
    url(r'^retrieve$', views.retrieve, name='retrieve'),
    url(r'^search/', search_views.MySearchView(), name='haystack_search'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'blog/login.html'}),
]

configs/urls.py
# coding:utf-8

"""blog_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from rest_framework import routers
from blog import views
from configs import settings

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    url(r'^admin/', include('admin.urls', namespace='admin', app_name='admin')),
    url(r'^api/', include(router.urls)),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    # 如果使用settings.MEDIA_ROOT,那么会上传到media/下，因为settings中的MEDIA_ROOT路径为../Blog/configs
    urlpatterns.append(url(r'^media/(?P<path>.*)$',
                           'django.views.static.serve', {'document_root':
                                                         settings.MEDIA_ROOT}))

apps/blog/forms.py
# coding:utf-8
from django import forms
from .models import Article, BlogComment


SEX_CHOICES = (
    ('male', '男'),
    ('female', '女')

)


class RegistForm(forms.Form):
    email = forms.EmailField(
        required=True, label='邮箱', error_messages={'required': '请输入邮箱'})
    username = forms.CharField(
        required=True, label='昵称 ', error_messages={'required': '请输入昵称'})
    password1 = forms.CharField(required=True, label='密码   ', widget=forms.PasswordInput(),
                                error_messages={'required': '请输入密码'})
    password2 = forms.CharField(required=True, label='确认密码', widget=forms.PasswordInput(),
                                error_messages={'required': '请再次输入密码'})
    sex = forms.ChoiceField(widget=forms.RadioSelect,
                            choices=SEX_CHOICES, label="性别")
    phone = forms.CharField(required=True, label='手机',
                            error_messages={'required': '请输入手机'})
    userimg = forms.ImageField(required=False, label='头像')


class UserForm(forms.Form):
    email = forms.EmailField(
        required=True, label='邮箱', error_messages={'required': '请输入邮箱'})
    password = forms.CharField(required=True, label='密码  ', widget=forms.PasswordInput(),
                               error_messages={'required': '请输入密码'})

    # def clean(self):
    #    if not self.is_valid():
    #        raise forms.ValidationError('用户名和密码为必填项')
    #    else:
    #        cleaned_data = super(UserForm, self).clean()


class RetrieveForm(forms.Form):
    username = forms.EmailField(
        required=True, label='邮箱', error_messages={'required': '请输入邮箱'})
    phone = forms.CharField(required=True, label='手机',
                            error_messages={'required': '请输入手机号'})
    password1 = forms.CharField(required=True, label='密码   ', widget=forms.PasswordInput(),
                                error_messages={'required': '请输入新密码'})
    password2 = forms.CharField(required=True, label='确认密码', widget=forms.PasswordInput(),
                                error_messages={'required': '请再次输入新密码'})


class SearchForm(forms.Form):
    body_search = forms.CharField(required=True)


class AttachmentForm(forms.Form):
    attachment = forms.FileInput()


class BlogCommentForm(forms.Form):
    body = forms.CharField(required=True, widget=forms.Textarea(
        attrs={'placeholder': '我来评两句~'}))

    '''class Meta:
        model = BlogComment
        
        fields = ['body']
        fields.is_required = True
        widgets = {'body': forms.Textarea(attrs={'placeholder': '我来评两句~'})}
        
        widgets = {
            'user_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "请输入昵称",
                'aria-describedby': "sizing-addon1",
            }),
            'user_email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "请输入邮箱",
                'aria-describedby': "sizing-addon1",
            }),
            'body': forms.Textarea(attrs={'placeholder': '我来评两句~'}),
        }
        '''

apps/blog/views.py
# coding:utf-8

import os
import sys
import logging
import json
import base64

from django.shortcuts import render_to_response, render, get_object_or_404, \
    HttpResponseRedirect, Http404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.contrib import auth
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required, permission_required
# from django.utils.decorators import method_decorator
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse
from django.core.cache import cache
from django.db.models import Q
from django.http import HttpResponse, FileResponse
from django.utils import timezone
# 缓存推荐在urls那里添加
from django.views.decorators.cache import cache_page  # 缓存

import qrcode
from cStringIO import StringIO
# import markdown2
from haystack.views import SearchView
from rest_framework import viewsets

from blog.serializers import UserSerializer, GroupSerializer
from blog.models import Article, Category, Tag, BlogComment, UserProfile, VisitorIP, Link 
from blog.tasks import save_client_ip
from .forms import RegistForm, UserForm, RetrieveForm, SearchForm, BlogCommentForm
from permission import check_blog_permission
from configs import settings
from utils.util import runTime, safeInt

# 代表本文件的绝对目录
BASEPATH = sys.path[0]
# 文件上传的目录
ATTACHMENT_PATH = os.path.join(settings.MEDIA_ROOT, 'blog/attachments')
USER_IMG_PATH = os.path.join(settings.MEDIA_ROOT, 'user/userimg')
USER_IMG_URL = os.path.join(settings.MEDIA_URL, 'user/userimg')
USER_IMG_MAX_SIZE = 1024 * 1024
DEFAULT_USER_IMG = 'defaultuser.png'
# 首页显示的评论字数
LENGTH_IN_RIGHT_INDEX = 14

logger = logging.getLogger('web')


@runTime
def add_views_or_likes(target_article, views_or_likes):
    # A likes add two weight, a view add one weight
    if views_or_likes == 'views':
        target_article.views += 1
        target_article.weight += 1
    else:
        target_article.likes += 1
        target_article.weight += 2
    return True


@runTime
def get_context_data_all(**kwargs):
    kwargs['category_list'] = Category.objects.all()
    kwargs['date_archive'] = Article.objects.archive()
    kwargs['tag_list'] = Tag.objects.all()
    kwargs['link_list'] = Link.objects.all()
    # logger.debug('link list: %s', kwargs['link_list'])
    visitor_ip = VisitorIP.objects.all()[:5]
    for visitor in visitor_ip:
        ip_split = visitor.ip.split('.')
        visitor.ip = '%s.*.*.%s' % (ip_split[0], ip_split[3])
        if not visitor.city:
            visitor.city = visitor.country
    kwargs['visitor_ip'] = visitor_ip
    kwargs['visitor_num'] = cache.get('visitor_num')
    recent_comment = BlogComment.objects.order_by('-created_time')[:5]
    for comment in recent_comment:
        if len(comment.body) > LENGTH_IN_RIGHT_INDEX:
            comment.body = comment.body[:LENGTH_IN_RIGHT_INDEX + 1] + '...'
    kwargs['recent_comment'] = recent_comment
    hot_article = Article.objects.filter(
        status='p').order_by('-weight', '-created_time')[:10]
    for article in hot_article:
        if len(article.title) > LENGTH_IN_RIGHT_INDEX:
            article.title = article.title[:LENGTH_IN_RIGHT_INDEX + 1] + '...'
    kwargs['hot_article'] = hot_article
    return kwargs


def get_client_ip(request):
    referer = request.META.get("HTTP_REFERER")
    if 'HTTP_X_FORWARDED_FOR' in request.META:
        ip = request.META['HTTP_X_FORWARDED_FOR']
    else:
        ip = request.META['REMOTE_ADDR']
    return ip, referer


class CachePageMixin(object):
    @classmethod
    def as_view(cls, **initkargs):
        view = super(CachePageMixin, cls).as_view(**initkargs)
        return cache_page(60 * 120)(view)


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

# LoginRequiredMixin放最左边,多重继承时有先后顺序，从右开始，广度优先


class AccountView(LoginRequiredMixin, ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        # 一篇文章多个评论，只能过滤出一个文章, distinct无参数,如果需要过滤具体的不重复参数（如不重复的title）,可以.values('title').distince()
        article_list = Article.objects.filter(
            comment__commentator__username=self.request.user.username, status='p').distinct()
        return article_list

    def get_context_data(self, **kwargs):
        kwargs = get_context_data_all()
        return super(AccountView, self).get_context_data(**kwargs)


class IndexView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        # models中已经定义了meta类，所以可以不用.order_by('name')
        # request在self中已经传入
        if self.request.user.is_superuser:
            article_list = Article.objects.filter(
                created_time__lte=timezone.now())
        else:
            article_list = Article.objects.filter(
                created_time__lte=timezone.now(), status='p')
        client_ip, referer = get_client_ip(self.request)
        save_client_ip.delay(client_ip, referer=referer)
        # cache.set('tcdlejl', 'value', timeout=100)
        # logging.info(cache.get('tcdlejl'))
        return article_list

    def get_context_data(self, **kwargs):
        kwargs = get_context_data_all()
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog/detail.html"
    context_object_name = "article"
    pk_url_kwarg = 'article_id'

    @runTime
    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        # 未发表文章不能显示
        if obj.status == 'd' and not self.request.user.is_superuser:
            raise Http404
        add_views_or_likes(target_article=obj, views_or_likes='views')
        obj.save()
        # obj.body = markdown2.markdown(
            # obj.body, ['codehilite'], extras=['fenced-code-blocks'])
        obj.attachment_url = obj.attachment_url.split('/')
        client_ip, referer = get_client_ip(self.request)
        save_client_ip.delay(client_ip, obj.id, referer=referer)
        logger.debug("get article: %s", self.kwargs[self.pk_url_kwarg])
        return obj

    @runTime
    def get_context_data(self, **kwargs):
        kwargs['comment_list'] = self.object.comment.all()
        kwargs['comment_nums'] = self.object.comment.count()
        kwargs['form'] = BlogCommentForm()
        kwargs['link_list'] = Link.objects.all()
        visitor_ip = VisitorIP.objects.filter(article=self.kwargs[self.pk_url_kwarg])[:5]
        visitor_ip = visitor_ip
        for visitor in visitor_ip:
            ip_split = visitor.ip.split('.')
            visitor.ip = '%s.*.*.%s' % (ip_split[0], ip_split[3])
            if not visitor.city:
                visitor.city = visitor.country
        kwargs['visitor_ip'] = visitor_ip
        return super(ArticleDetailView, self).get_context_data(**kwargs)


@login_required
@runTime
def upload(request, article_id):
    article_url = reverse('blog:detail', args=(article_id,))
    result = {"upload_info": "上传成功"}
    if request.method == 'GET':
        return HttpResponseRedirect(article_url)
    else:
        target_article = get_object_or_404(Article, pk=article_id)
        if target_article.status == 'd' and not request.user.is_superuser:
            return HttpResponseRedirect('/')
        myfile = request.FILES.get('uploadfile', None)
        if not myfile:
            result["upload_info"] = 'No upload files!'
            return render(request, 'blog/upload.html', result)
        myfilename = myfile.name
        logger.info('upload filename: %s', myfilename)
        filename_error = os.path.sep in myfilename
        if filename_error:
            result["upload_info"] = 'File name error!'
            return render(request, 'blog/upload.html', result)
        folderpath = os.path.join(ATTACHMENT_PATH, str(article_id))
        try:
            os.mkdir(folderpath)
        except OSError, e:
            logging.error(e)
        filepath = os.path.join(folderpath, myfilename)
        logger.info('upload filepath: %s', filepath)
        with open(filepath, 'wb') as f:
            if myfile.multiple_chunks():
                f.write(myfile.read())
            else:
                for chunk in myfile.chunks():
                    f.write(chunk)
        # Remove the same filename, and attachment_url should split in
        # case of new filename is part of old filename
        if myfilename in target_article.attachment_url.split('/'):
            # Because the name exists, so attachment_url shouldn't change
            logging.warn('File exists, and will remove old file')
        else:
            target_article.attachment_url = myfilename + '/' \
                    + target_article.attachment_url
        target_article.save()
        return render(request, 'blog/upload.html', result)


# arguments can be:login_url, raise_exception
# or can use permission.py, @perm_check
# @permission_required('blog.download_file', raise_exception=True)

@login_required
@runTime
def download(request, param1, param2):
    article_id = param1
    file_id = int(param2)
    article_url = reverse('blog:detail', args=(article_id,))
    if request.method == 'POST':
        return HttpResponseRedirect(article_url)
    else:
        target_article = get_object_or_404(Article, pk=article_id)
        if target_article.status == 'd' and not request.user.is_superuser:
            return HttpResponseRedirect('/')

        def file_iterator(file_name, chunk_size=512):
            with open(file_name, 'rb') as f:
                while True:
                    c = f.read(chunk_size)
                    if c:
                        yield c
                    else:
                        break
        user_id = str(request.user.id)

apps/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name='keywords' content="技术博客,低调诺,程序员,码农,">
    <meta name='author' content="低调诺">
    <meta name='description' content="一个程序员的技术积累，包括各种各样的问题">
    <title>低调诺的博客</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'blog/img/favicon.ico' %}" media="screen" />
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'lib/css/bootstrap.min.css' %}">
	<style type="text/css">
		body { background: #000; margin: 0; padding:0; }
		canvas {position: fixed; z-index: -1}
	</style>
    <script type="text/javascript" src="{% static 'blog/js/jquery.min.js' %}"></script>
	 {% block custom_css %}{% endblock %}
    <!--script type="text/javascript" src="{% static 'blog/js/ajaxdebug.js' %}"></script-->
</head>
<body>
<canvas id='canvas'></canvas>
<div id="header" class="transparent">
    <div id="header-warp">
        <a href="/admin" title="我的博客" id="logo"></a>
        
        <ul id="header-nav">
            <li><a href="{% url 'blog:index' %}">首页</a></li>
        </ul>
        <div id="header-right" class="login">
            <div class="user">
            {# 不可使用request.session['username'], 模板中的语句都不带参数 #}
            {#%  if user.is_authenticated %#}
            {% if request.session.username %}
                <div id='userimgdiv'>
                    <img class='img-circle' id='userimg' src="{{ MEDIAURL }}{{ request.session.userimg }}" alt='头像'>
                </div>
                <a id='username' href="{% url 'blog:logout' %}" float:left>{{ request.session.username }}</a>
                <a id='usercomment' href="{% url 'blog:account' %}">评论过的文章</a>
            {% else %}
                <a href="{% url 'blog:regist' %}">注册</a>
                <a href="{% url 'blog:login' %}">登陆</a>
            {% endif %}
            </div>
            
        </div>
        <div id='header-middle' class='qrcode'>
            <!--form method='post' action='{% url "blog:qrcode" %}'-->
            <form method='post' action='{% url "blog:qrcode" %}'>
               {% csrf_token %}
                <input name='target_url' type='text' placeholder="默认为当前网址">
                <input type='button' class='generate_qrcode' value="生成二维码" >
                <!--下面的方法会报错，ajaxStart状态出问题,因为button在firefox中默认type=submit,并且还漏了</button>
                <button class='generate_qrcode'value="生成二维码" onclick='submit_qrcode()'>
                -->
            </form>
            <form method='get' action='{% url "blog:haystack_search" %}'>
               {% csrf_token %}
                <input name='q' id='id_q' placeholder="输入要搜索的关键字">
                <input id='search' value="搜索" type='submit'>
            </form>
        </div>
    </div>
    
</div>

{% block content %}{% endblock %}
<div class="row" id="friend">
  {% for link in link_list %}
  <div class="col-md-1">
		<a class="friend-url" href="{{ link.url }}" target="_blank" title={{ link.description }}>{{ link.name }}</a>
  </div>
  {% endfor %}
</div>

<div class="row">
  <div class="col-md-5 col-md-offset-3">Copyright © 2006-2016 caitinggui(caitinggui@qq.com).All Rights Reserved</div>
</div>
<div class="row">
  <div class="col-md-3 col-md-offset-3">
      <a href="http://www.miitbeian.gov.cn" target="_blank">粤ICP备16122044号</a>
  </div>
  <div class="col-md-2">
      <a href="mailto:caitinggui@qq.com">联系我</a>
  </div>
</div>
</body>

<script type="text/javascript" src="{% static 'blog/js/django.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/js/base.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/js/canvas-background.js' %}"></script>
{% block custom_js %}{% endblock %}
</html>

apps/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
    <!--<div id="banner" class="noselect"></div> -->

    <div class="container transparent">
        <div class="row">
            <div class="col-lg-9">
                <div id="category" class="noselect">
                    <div id="category-title">
                        <ul>
                            <li>分类：</li>
                            {% for category in category_list %}
                                <li class="cat-item"><a
                                        href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div id="bd" class="wrp clear-fix">
                    <div id="main">
                        {% if query %}  
                            <h3 class="obvious-color">搜索结果</h3>
                            {% load highlight %}
                            {% for result in page.object_list %}  
                              <div class="post">
                                <div class="post-hd">
                                    <h1 class="title">
                                        <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
                                    </h1>
                                </div>   
                                <div class="post-bd">
                                    {% highlight result.object.body with query css_class "highlight_me_please" max_length 200 %}
                                </div>
                              </div>
                            {% empty %}  
                              <div class="post">
                                <p>抱歉，没有搜索到结果，请更换关键词重新搜索~</p>
                              </div>
                            {% endfor %}  

                            {% if page.has_previous or page.has_next %}  
                                <div>  
                                    {% if page.has_previous %}
																		  <a class='obvious-color' href="?q={{ query }}&page={{ page.previous_page_number }}">« Previous |</a>
																		{% endif %}  
                                    {% if page.has_next %}
																		  <a class='obvious-color' href="?q={{ query }}&page={{ page.next_page_number }}">Next »</a>
																		{% endif %}  
                                </div>  
                            {% endif %}  
                        {% else %}  
                            {% load paginate_tags %}
                            {% paginate article_list 9 %}
                            {% for article in article_list %}
                                <div class="post">
                                    <div class="post-hd">
                                        <h1 class="title"><a
                                                href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h1>
                                    </div>
                                    <div class="post-bd">
                                        <p>{{ article.abstract }}</p>
                                        <p><a href="" class="more-link"></a></p>
                                    </div>
                                    <div class="post-ft">
                                        <a href="{% url 'blog:detail' article.id %}" class="more">阅读全文>></a>
                                        <i class="icon-date"></i>
                                        <span class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                                        <!--i class='icon-praise'></i>-->
                                        <input type='image' class='praise' src="{% static 'blog/img/gb21.png' %}" href="{% url 'blog:detail' article.id %}/praise">
                                        <span class='likes_num'>{{ article.likes}}</span>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <a href="/admin/article/edit/?aid={{ article.pk }}">编辑</a>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <span>阅读量:{{ article.views}}</span>
                                    </div>
                                </div>
                            {% endfor %}
                            {% include 'blog/pagination.html' %}
                        {% endif %}  
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <!-- tags -->
                <h3 class="obvious-color">标签:</h3>
                <div  id="cloudtag">
                    {% for tag in tag_list %}
					<a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                    {% endfor %}
                </div>

                <!-- archive -->
                <h3 class="obvious-color">文章归档：</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for year,months in date_archive %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                        {{ year }} 年
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for month in months %}
                                        <a href="{% url 'blog:archive' year month %}"><p>{{ month }} 月</p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <h3 class="obvious-color">热门文章：</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for article in hot_article %}
                                        <a href="{% url 'blog:detail' article.id %}"><p>{{ article.title|truncatewords:2 }}</p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                </div>
                <h3 class="obvious-color">最新评论：</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for comment in recent_comment %}
                                        <a href="{% url 'blog:detail' comment.article.id %}"><p>{{ comment.body }}</p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                </div>
                <h3 class="obvious-color">最近访问</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}"> 访问量:{{ visitor_num }}
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for visitor in visitor_ip %}
                                        <p>{{ visitor.ip }}[{{ visitor.city }}]  <sup>{{ visitor.visited_time | date:'m-j H:i'}}</sup></p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_css %}
<style type="text/css">
#cloudtag {position:relative; width:260px; height:260px; solid #000; margin: 20px auto 0;}
#cloudtag a {position:absolute; top:0px; left:0px; color:#00FF00; font-weight:bold; text-decoration:none; padding: 3px 6px; }
#cloudtag a:hover {border: 1px solid #eee; background: #000; }
</style>
{% endblock %}

{% block custom_js %}
<script type="text/javascript" src="{% static 'blog/js/jquery.windstagball.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
    $("#cloudtag").windstagball({
            radius:120,
            speed:10
        });
    });
</script>
{% endblock %}